version: '3.8'

services:
  rest-service:
    build:
      context: .  # Root of the project
      dockerfile: REST-Service/Dockerfile  # Path to Dockerfile for REST service
    ports:
      - "8001:8001"
    networks:
      - my-network

  graphql-service:
    build:
      context: .  # Root of the project
      dockerfile: GRAPHQL-service/Dockerfile  # Path to Dockerfile for GraphQL service
    ports:
      - "8002:8002"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
