trigger:
  branches:
    include:
      - main
      - develop

pool: MyAgentPool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- script: dotnet build
  displayName: 'Build Solution'

- script: dotnet test
  displayName: 'Run Unit Tests'

- task: SonarQubePrepare@7
  inputs:
    SonarQube: '<SonarQube Service Connection>'
    scannerMode: 'MSBuild'
    configMode: 'manual'
    projectKey: 'MyProjectKey'
    projectName: 'MyProject'

- task: SonarQubeAnalyze@7

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    repository: '<repository-name>'
    tags: 'latest'
