trigger:
- main  # Déclenchement de la pipeline sur la branche "main"

pool:
  vmImage: 'ubuntu-latest'  # Choix de l'image d'agent

steps:
- task: UsePythonVersion@1  # Configuration de l'environnement Python (facultatif, selon vos besoins)
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo "Installing dependencies"
    pip install -r requirements.txt
    echo "Running tests"
    pytest
  displayName: 'Install dependencies and run tests'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: 'Container'
